version: "3.1"
services:
  reguest:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - "./code:/app"
    ports:
      - "8085:8080"
    links:
      - backend
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - "FLAG=ENO{TESTFLAG}"
    volumes:
      - "./code:/app"