version: '3.8'

services:
  flaskapp:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "1338:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
  